<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policymap [
<!ELEMENT policymap (policy)+>
<!ELEMENT policy (#PCDATA)>
<!ATTLIST policy domain (delegate|coder|filter|path|resource) #IMPLIED>
<!ATTLIST policy name CDATA #IMPLIED>
<!ATTLIST policy rights CDATA #IMPLIED>
<!ATTLIST policy pattern CDATA #IMPLIED>
<!ATTLIST policy value CDATA #IMPLIED>
]>

<policymap>
  <policy domain="resource" name="memory" value="1GB"/>
  <policy domain="resource" name="map" value="1GB"/>
  <policy domain="resource" name="width" value="16KP"/>
  <policy domain="resource" name="height" value="16KP"/>
  <policy domain="resource" name="area" value="128MB"/>
  <policy domain="resource" name="disk" value="10GiB"/>
  <policy domain="delegate" rights="none" pattern="URL" />
  <policy domain="delegate" rights="none" pattern="HTTPS" />
  <policy domain="delegate" rights="none" pattern="HTTP" />
  <policy domain="path" rights="none" pattern="@*"/>
  <policy domain="cache" name="shared-secret" value="passphrase" stealth="true"/>
  <policy domain="coder" rights="none" pattern="PS" />
  <policy domain="coder" rights="none" pattern="PS2" />
  <policy domain="coder" rights="none" pattern="PS3" />
  <policy domain="coder" rights="none" pattern="EPS" />
  <policy domain="coder" rights="read|write" pattern="PDF" />
  <policy domain="coder" rights="none" pattern="XPS" />
  <policy pattern="EPHEMERAL" domain="coder" rights="none"></policy>
  <policy pattern="URL" domain="coder" rights="none"></policy>
  <policy pattern="HTTPS" domain="coder" rights="none"></policy>
  <policy pattern="MVG" domain="coder" rights="none"></policy>
  <policy pattern="MSL" domain="coder" rights="none"></policy>
  <policy pattern="TEXT" domain="coder" rights="none"></policy>
  <policy pattern="SHOW" domain="coder" rights="none"></policy>
  <policy pattern="WIN" domain="coder" rights="none"></policy>
  <policy pattern="PLT" domain="coder" rights="none"></policy>
</policymap>
